from rest_framework import serializers
from django.utils import timezone
from .models import ChatMessage, Session
import uuid


class ChatRequestSerializer(serializers.Serializer):
    """
    Serializer for chat request (both streaming and non-streaming).
    Used for Swagger documentation to properly display request body.
    """
    message = serializers.CharField(
        required=True,
        help_text="User message to send to the assistant"
    )
    session_id = serializers.CharField(
        required=True,
        help_text="Session ID (required). Must be a valid, active, and non-expired session."
    )


class SessionSerializer(serializers.ModelSerializer):
    """
    Serializer for Session model.
    
    The id field (UUID) serves as the session identifier.
    No user_id required. expires_at is optional (auto-generated if not provided).
    """
    expires_at = serializers.DateTimeField(required=False, allow_null=True, help_text="Expiration time (optional, defaults to 24h from now)")
    
    class Meta:
        model = Session
        fields = ['id', 'external_user_id', 'created_at', 
                  'expires_at', 'is_active', 'metadata']
        read_only_fields = ['id', 'created_at']
    
    def create(self, validated_data):
        """Create session. id (UUID) is auto-generated as primary key. expires_at will be set by model's save() method if not provided."""
        # id is auto-generated by UUIDField default, expires_at will be set by model's save()
        return super().create(validated_data)


class ChatMessageSerializer(serializers.ModelSerializer):
    """
    Serializer for ChatMessage model.
    
    Session details are excluded from the response - only session_id (UUID) is shown.
    Only user and assistant messages are returned (system messages are excluded).
    """
    session_id = serializers.UUIDField(
        source='session.id',
        read_only=True,
        help_text="Session ID (read-only UUID)"
    )
    
    class Meta:
        model = ChatMessage
        fields = ['id', 'session_id', 'message', 'role', 'metadata', 'timestamp']
        read_only_fields = ['id', 'session_id', 'timestamp']
        # Exclude is_deleted from response - we only show non-deleted messages
