"""
Django settings for whipsmart_admin project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-z)$&r+fl&xy#w&_hnyx(1ny$q=$nhygdy&mwi@v$_7&i(40zx_')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Allow all hosts (both development and production)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=lambda v: ['*'] if v == '*' else [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',
    'channels',
    
    # Local apps
    'core',
    'knowledgebase',
    'chats',
    'widget',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise for static files (Heroku)
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware should be early
    'widget.middleware.APIKeyAuthenticationMiddleware',  # API key authentication for widget endpoints
    'core.middleware.DisableCSRFForAPI',  # Disable CSRF for API endpoints
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'whipsmart_admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'whipsmart_admin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Determine database engine from environment
DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')

if DB_ENGINE == 'django.db.backends.mysql':
    # MySQL Configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('DB_NAME', default='whipsmart_db'),
            'USER': config('DB_USER', default='root'),
            'PASSWORD': config('DB_PASSWORD', default='root'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='3306', cast=int),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
                'autocommit': True,
            },
            'CONN_MAX_AGE': 600,  # Connection pooling
        }
    }

# Custom User Model
AUTH_USER_MODEL = 'core.AdminUser'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for Heroku
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
    # Disable format suffixes to prevent "Converter already registered" error with multiple routers
    'URL_FORMAT_OVERRIDE': None,
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Whipsmart Admin Panel API',
    'DESCRIPTION': 'Complete Django backend for Whipsmart Admin Panel with admin authentication, knowledgebase management, and agentic chatbot sessions.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'Bearer': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'JWT token authentication. Format: "Bearer <your_access_token>"',
            },
        }
    },
    'TAGS': [
        {'name': 'Authentication', 'description': 'Admin user authentication endpoints'},
        {'name': 'Users', 'description': 'Admin user management'},
        {'name': 'Visitors', 'description': 'Visitor ID management - STEP 1: Create visitor before creating sessions'},
        {'name': 'Sessions', 'description': 'Chat session management - STEP 2: Create session with visitor_id'},
        {'name': 'Messages', 'description': 'Chat message management - STEP 3: Send messages with visitor_id and session_id'},
        {'name': 'Documents', 'description': 'Document upload and management'},
        {'name': 'Knowledgebase', 'description': 'Knowledgebase statistics and utilities'},
        {'name': 'Widget API Keys', 'description': 'Widget API key management endpoints'},
        {'name': 'Widget', 'description': 'Widget configuration and embed code endpoints'},
    ],
    'TAG_ORDER': ['Authentication', 'Users', 'Visitors', 'Sessions', 'Messages', 'Documents', 'Knowledgebase', 'Widget API Keys', 'Widget'],
}

# CORS settings - Allow all origins
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins (enable for development)
CORS_ALLOW_CREDENTIALS = True  # Allow cookies/auth headers

# Optional: Specific origins (commented out when CORS_ALLOW_ALL_ORIGINS = True)
# CORS_ALLOWED_ORIGINS = config(
#     'CORS_ALLOWED_ORIGINS',
#     default='http://localhost:3000,http://127.0.0.1:3000',
#     cast=lambda v: [s.strip() for s in v.split(',')]
# )

# Additional CORS settings for full access
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-api-key',  # Widget API key authentication header
]

# CORS settings for static files (JavaScript, CSS, etc.)
# Note: django-cors-headers applies to views, but for static files served directly,
# you may need to configure your web server (nginx/Apache) or use WhiteNoise with CORS
# For widget-loader.js served via views, CORS headers are set explicitly in the view
CORS_EXPOSE_HEADERS = [
    'content-type',
    'content-length',
    'x-ratelimit-limit',
    'x-ratelimit-remaining',
    'x-ratelimit-reset',
]

# CSRF settings - Allow all origins
# Note: API endpoints (/api/*) are exempt from CSRF via middleware (using JWT auth)
# For widget endpoints, we allow all origins
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='https://chatbot-widget.novuscode.in,https://whipsmart-admin-panel-921aed6c92cf.herokuapp.com,http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173,http://localhost:8000,http://127.0.0.1:8000',
    cast=lambda v: [s.strip() for s in v.split(',')] if v else []
)

# CSRF cookie settings (for development)
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'

# Allow all origins in development mode
# For REST APIs using JWT authentication, CSRF is not required
# The middleware DisableCSRFForAPI disables CSRF for /api/ endpoints
if DEBUG:
    # Add all common localhost variations
    additional_origins = [
        'http://localhost',
        'http://127.0.0.1',
    ]
    CSRF_TRUSTED_ORIGINS = list(CSRF_TRUSTED_ORIGINS) + additional_origins

# Pinecone settings
PINECONE_API_KEY = config('PINECONE_API_KEY', default='')
PINECONE_ENVIRONMENT = config('PINECONE_ENVIRONMENT', default='')
PINECONE_INDEX_NAME = config('PINECONE_INDEX_NAME', default='whipsmart-docs')

# OpenAI settings (for embeddings if not using Azure)
OPENAI_API_KEY = config('OPENAI_API_KEY', default='')

# Azure OpenAI settings
AZURE_OPENAI_API_KEY = config('AZURE_OPENAI_API_KEY', default='')
AZURE_OPENAI_ENDPOINT = config('AZURE_OPENAI_ENDPOINT', default='')
AZURE_OPENAI_DEPLOYMENT_NAME = config('AZURE_OPENAI_DEPLOYMENT_NAME', default='')
AZURE_OPENAI_API_VERSION = config('AZURE_OPENAI_API_VERSION', default='2024-02-15-preview')

# Azure OpenAI Embedding settings (separate from chat/completion)
AZURE_EMBEDDING_API_KEY = config('AZURE_EMBEDDING_API_KEY', default='')
AZURE_EMBEDDING_API_URI = config('AZURE_EMBEDDING_API_URI', default='')
AZURE_EMBEDDING_API_VERSION = config('AZURE_EMBEDDING_API_VERSION', default='2024-02-15-preview')
AZURE_OPENAI_EMBEDDING_DEPLOYMENT = config('AZURE_OPENAI_EMBEDDING_DEPLOYMENT', default='')

# OpenAI settings (for embeddings if not using Azure)
OPENAI_API_KEY = config('OPENAI_API_KEY', default='')

# Cloud Storage Configuration (for future use)
# Currently using local media folder, but ready for cloud storage
USE_CLOUD_STORAGE = config('USE_CLOUD_STORAGE', default=False, cast=bool)
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default='')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')
# For Azure Blob Storage
AZURE_STORAGE_ACCOUNT_NAME = config('AZURE_STORAGE_ACCOUNT_NAME', default='')
AZURE_STORAGE_ACCOUNT_KEY = config('AZURE_STORAGE_ACCOUNT_KEY', default='')
AZURE_STORAGE_CONTAINER_NAME = config('AZURE_STORAGE_CONTAINER_NAME', default='')

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'agent.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'chats': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'agents': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'knowledgebase': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'widget': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Widget API Key Configuration
API_KEY_PREFIX_LIVE = config('API_KEY_PREFIX_LIVE', default='sk_live_')
API_KEY_PREFIX_TEST = config('API_KEY_PREFIX_TEST', default='sk_test_')
API_KEY_MIN_LENGTH = config('API_KEY_MIN_LENGTH', default=32, cast=int)
API_KEY_HASH_ROUNDS = config('API_KEY_HASH_ROUNDS', default=12, cast=int)

# Widget CDN URLs
WIDGET_CDN_URL = config('WIDGET_CDN_URL', default='https://cdn.yourdomain.com/widget')
WIDGET_LOADER_URL = config('WIDGET_LOADER_URL', default='https://cdn.yourdomain.com/widget-loader.js')
WIDGET_API_URL = config('WIDGET_API_URL', default='https://api.yourdomain.com')

# Rate Limiting Configuration
RATE_LIMIT_WIDGET_CONFIG = config('RATE_LIMIT_WIDGET_CONFIG', default=100, cast=int)  # per hour
RATE_LIMIT_CHAT_API = config('RATE_LIMIT_CHAT_API', default=1000, cast=int)  # per hour
RATE_LIMIT_MESSAGES = config('RATE_LIMIT_MESSAGES', default=100, cast=int)  # per minute

# Cache Configuration (for rate limiting)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 3600,  # Default timeout: 1 hour
        'OPTIONS': {
            'MAX_ENTRIES': 10000
        }
    }
}

# For production, use Redis instead:
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': config('REDIS_URL', default='redis://127.0.0.1:6379/1'),
#     }
# }

# Channels Configuration
ASGI_APPLICATION = 'whipsmart_admin.asgi.application'

# Channel Layers Configuration
# Try Redis first, fallback to InMemoryChannelLayer if Redis is not available or incompatible
try:
    import redis
    redis_client = redis.Redis(host='127.0.0.1', port=6379, db=0, socket_connect_timeout=1)
    redis_client.ping()
    
    # Check Redis version - BZPOPMIN requires Redis 5.0+
    try:
        redis_info = redis_client.info('server')
        redis_version = redis_info.get('redis_version', '0.0.0')
        version_parts = redis_version.split('.')
        major_version = int(version_parts[0]) if version_parts else 0
        
        if major_version < 5:
            raise Exception(f"Redis version {redis_version} is too old. Redis 5.0+ required for BZPOPMIN command.")
        
        # Redis is available and compatible - use RedisChannelLayer
        CHANNEL_LAYERS = {
            'default': {
                'BACKEND': 'channels_redis.core.RedisChannelLayer',
                'CONFIG': {
                    "hosts": [config('REDIS_URL', default='redis://127.0.0.1:6379/0')],
                },
            },
        }
    except Exception as e:
        # Redis version check failed or version too old
        import warnings
        warnings.warn(
            f"Redis version incompatible or check failed: {e}. "
            "Using InMemoryChannelLayer. For production, use Redis 5.0+."
        )
        CHANNEL_LAYERS = {
            'default': {
                'BACKEND': 'channels.layers.InMemoryChannelLayer',
            },
        }
except Exception as e:
    # Redis not available - use InMemoryChannelLayer for development
    import warnings
    warnings.warn(
        f"Redis is not available: {e}. Using InMemoryChannelLayer. "
        "WebSocket support may be limited. Install Redis 5.0+ for production use."
    )
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
