# Generated by Django 5.2.8 on 2025-11-28 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text'), ('docx', 'Word Document'), ('html', 'HTML')], max_length=10)),
                ('vector_id', models.CharField(blank=True, help_text='Pinecone vector ID', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the document is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vector_id'], name='knowledgeba_vector__51d840_idx'), models.Index(fields=['file_type'], name='knowledgeba_file_ty_e2c5ad_idx'), models.Index(fields=['is_active'], name='knowledgeba_is_acti_a98975_idx')],
            },
        ),
    ]
