# Generated by Django 5.2.8 on 2025-11-28 11:39

from django.db import migrations, models


def fix_migration(apps, schema_editor):
    """Fix migration - drop index first, then alter field, then add new fields."""
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        # Step 1: Drop index on vector_id if it exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.STATISTICS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'knowledgebase_document'
            AND INDEX_NAME LIKE '%vector%'
        """)
        if cursor.fetchone()[0] > 0:
            # Find and drop the index
            cursor.execute("""
                SELECT INDEX_NAME 
                FROM information_schema.STATISTICS 
                WHERE TABLE_SCHEMA = DATABASE()
                AND TABLE_NAME = 'knowledgebase_document'
                AND INDEX_NAME LIKE '%vector%'
                LIMIT 1
            """)
            result = cursor.fetchone()
            if result:
                index_name = result[0]
                cursor.execute(f"ALTER TABLE knowledgebase_document DROP INDEX {index_name}")
        
        # Step 2: Alter vector_id to TEXT (if not already TEXT)
        cursor.execute("""
            SELECT DATA_TYPE 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'knowledgebase_document'
            AND COLUMN_NAME = 'vector_id'
        """)
        result = cursor.fetchone()
        if result and result[0] != 'text':
            cursor.execute("""
                ALTER TABLE knowledgebase_document 
                MODIFY COLUMN vector_id TEXT NULL
            """)
        
        # Step 3: Add is_vectorized if it doesn't exist
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'knowledgebase_document'
            AND COLUMN_NAME = 'is_vectorized'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE knowledgebase_document 
                ADD COLUMN is_vectorized BOOLEAN DEFAULT FALSE
            """)
        
        # Step 4: Add vectorized_at if it doesn't exist
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'knowledgebase_document'
            AND COLUMN_NAME = 'vectorized_at'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE knowledgebase_document 
                ADD COLUMN vectorized_at DATETIME(6) NULL
            """)


def reverse_migration(apps, schema_editor):
    """Reverse migration."""
    with schema_editor.connection.cursor() as cursor:
        # This is a one-way migration for fixing existing database
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fix_migration, reverse_migration),
    ]
