# Generated by Django 5.2.8 on 2025-11-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0002_document_is_vectorized_document_vectorized_at_and_more'),
    ]

    operations = [
    ]
