# Generated by Django 5.2.8 on 2025-11-28 12:05

from django.conf import settings
from django.db import migrations, models


def fix_index_migration(apps, schema_editor):
    """Fix index migration - drop old index if exists, add new index."""
    with schema_editor.connection.cursor() as cursor:
        # Step 1: Drop old index if it exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.STATISTICS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'knowledgebase_document'
            AND INDEX_NAME = 'knowledgeba_vector__51d840_idx'
        """)
        if cursor.fetchone()[0] > 0:
            cursor.execute("ALTER TABLE knowledgebase_document DROP INDEX knowledgeba_vector__51d840_idx")
        
        # Step 2: Add new index on is_vectorized if it doesn't exist
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.STATISTICS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'knowledgebase_document'
            AND INDEX_NAME = 'knowledgeba_is_vect_168322_idx'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                CREATE INDEX knowledgeba_is_vect_168322_idx 
                ON knowledgebase_document (is_vectorized)
            """)


def reverse_migration(apps, schema_editor):
    """Reverse migration."""
    with schema_editor.connection.cursor() as cursor:
        # Drop new index if exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.STATISTICS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'knowledgebase_document'
            AND INDEX_NAME = 'knowledgeba_is_vect_168322_idx'
        """)
        if cursor.fetchone()[0] > 0:
            cursor.execute("ALTER TABLE knowledgebase_document DROP INDEX knowledgeba_is_vect_168322_idx")


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0003_auto_20251128_1728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(fix_index_migration, reverse_migration),
    ]
