# Generated by Django 5.2.8 on 2025-11-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0004_remove_document_knowledgeba_vector__51d840_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_url',
            field=models.URLField(blank=True, help_text='Cloud storage URL (if using cloud storage)', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Document file (supports local media folder and cloud storage)', upload_to='documents/%Y/%m/%d/'),
        ),
    ]
