# Generated by Django 5.2.8 on 2025-11-28 12:29

from django.conf import settings
from django.db import migrations, models


def fix_duplicate_migration(apps, schema_editor):
    """Fix duplicate migration - check if operations already done."""
    with schema_editor.connection.cursor() as cursor:
        # Step 1: Remove old index if it exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.STATISTICS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'knowledgebase_document'
            AND INDEX_NAME = 'knowledgeba_vector__51d840_idx'
        """)
        if cursor.fetchone()[0] > 0:
            cursor.execute("ALTER TABLE knowledgebase_document DROP INDEX knowledgeba_vector__51d840_idx")
        
        # Step 2: Add is_vectorized if it doesn't exist
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'knowledgebase_document'
            AND COLUMN_NAME = 'is_vectorized'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE knowledgebase_document 
                ADD COLUMN is_vectorized BOOLEAN DEFAULT FALSE
            """)
        
        # Step 3: Add vectorized_at if it doesn't exist
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'knowledgebase_document'
            AND COLUMN_NAME = 'vectorized_at'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE knowledgebase_document 
                ADD COLUMN vectorized_at DATETIME(6) NULL
            """)
        
        # Step 4: Alter vector_id to TEXT if not already TEXT
        cursor.execute("""
            SELECT DATA_TYPE 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'knowledgebase_document'
            AND COLUMN_NAME = 'vector_id'
        """)
        result = cursor.fetchone()
        if result and result[0] != 'text':
            cursor.execute("""
                ALTER TABLE knowledgebase_document 
                MODIFY COLUMN vector_id TEXT NULL
            """)
        
        # Step 5: Add index on is_vectorized if it doesn't exist
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.STATISTICS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'knowledgebase_document'
            AND INDEX_NAME = 'knowledgeba_is_vect_168322_idx'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                CREATE INDEX knowledgeba_is_vect_168322_idx 
                ON knowledgebase_document (is_vectorized)
            """)


def reverse_migration(apps, schema_editor):
    """Reverse migration."""
    with schema_editor.connection.cursor() as cursor:
        # Drop index if exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.STATISTICS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'knowledgebase_document'
            AND INDEX_NAME = 'knowledgeba_is_vect_168322_idx'
        """)
        if cursor.fetchone()[0] > 0:
            cursor.execute("ALTER TABLE knowledgebase_document DROP INDEX knowledgeba_is_vect_168322_idx")


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0005_document_file_url_alter_document_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(fix_duplicate_migration, reverse_migration),
    ]
