# Generated by Django 5.2.8 on 2025-11-28 12:37

from django.conf import settings
from django.db import migrations, models


def check_and_apply_changes(apps, schema_editor):
    """Check if changes are needed and apply them."""
    # All changes are already in the database from previous migrations
    # This is just to sync Django's migration state
    pass


def reverse_migration(apps, schema_editor):
    """Reverse migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0007_remove_document_knowledgeba_vector__51d840_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Use SeparateDatabaseAndState to tell Django about state changes
        # without actually modifying the database (since it's already done)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Database operations are already done, so we do nothing
            ],
            state_operations=[
                # Tell Django about the state changes
                migrations.RemoveIndex(
                    model_name='document',
                    name='knowledgeba_vector__51d840_idx',
                ),
                migrations.AddField(
                    model_name='document',
                    name='is_vectorized',
                    field=models.BooleanField(default=False, help_text='Whether document has been vectorized'),
                ),
                migrations.AddField(
                    model_name='document',
                    name='vectorized_at',
                    field=models.DateTimeField(blank=True, help_text='When document was vectorized', null=True),
                ),
                migrations.AlterField(
                    model_name='document',
                    name='vector_id',
                    field=models.TextField(blank=True, help_text='Pinecone vector IDs (comma-separated)', null=True),
                ),
                migrations.AddIndex(
                    model_name='document',
                    index=models.Index(fields=['is_vectorized'], name='knowledgeba_is_vect_168322_idx'),
                ),
            ],
        ),
    ]
