# Generated by Django 5.2.8 on 2025-11-28 12:45

from django.db import migrations, models
from django.conf import settings


def migrate_file_to_file_url(apps, schema_editor):
    """
    Migrate existing file field data to file_url.
    For existing documents, generate file_url from file field if it exists.
    """
    Document = apps.get_model('knowledgebase', 'Document')
    
    with schema_editor.connection.cursor() as cursor:
        # Check if file column exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'knowledgebase_document'
            AND COLUMN_NAME = 'file'
        """)
        file_exists = cursor.fetchone()[0] > 0
        
        if file_exists:
            # Update file_url for existing documents that have file but no file_url
            cursor.execute("""
                UPDATE knowledgebase_document 
                SET file_url = CONCAT('http://localhost:8000/media/', file)
                WHERE (file_url IS NULL OR file_url = '') 
                AND file IS NOT NULL 
                AND file != ''
            """)
            
            # For any remaining NULL file_url, set a placeholder
            cursor.execute("""
                UPDATE knowledgebase_document 
                SET file_url = CONCAT('http://localhost:8000/media/placeholder-', id, '.txt')
                WHERE file_url IS NULL OR file_url = ''
            """)


def reverse_migration(apps, schema_editor):
    """Reverse migration - not fully reversible."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0008_remove_document_knowledgeba_vector__51d840_idx_and_more'),
    ]

    operations = [
        # Step 1: Migrate existing file data to file_url
        migrations.RunPython(migrate_file_to_file_url, reverse_migration),
        
        # Step 2: Make file_url non-nullable
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.URLField(help_text='URL to the document file (stored in media folder)'),
        ),
        
        # Step 3: Remove file field
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
