# Generated by Django 5.2.8 on 2025-12-01 04:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0009_remove_file_add_file_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_id', models.CharField(help_text='Unique chunk identifier (format: {document_id}-chunk-{index})', max_length=255)),
                ('chunk_index', models.IntegerField(help_text='Index of chunk in the document')),
                ('text', models.TextField(help_text='Text content of the chunk')),
                ('text_length', models.IntegerField(help_text='Length of chunk text in characters')),
                ('is_vectorized', models.BooleanField(default=False, help_text='Whether chunk has been vectorized')),
                ('vector_id', models.CharField(blank=True, help_text='Pinecone vector ID for this chunk', max_length=255, null=True)),
                ('vectorized_at', models.DateTimeField(blank=True, help_text='When chunk was vectorized', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Metadata for the chunk (document_id, title, file_type, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='chunk_count',
            field=models.IntegerField(default=0, help_text='Number of chunks created'),
        ),
        migrations.AddField(
            model_name='document',
            name='state',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('chunked', 'Chunked'), ('processing', 'Processing'), ('live', 'Live'), ('removed_from_vectordb', 'RemovedFromVectorDB'), ('deleted', 'Deleted')], default='uploaded', help_text='Current state of the document in the lifecycle', max_length=30),
        ),
        migrations.AddField(
            model_name='document',
            name='upload_idempotency_key',
            field=models.CharField(blank=True, help_text='Idempotency key for upload operations', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='vector_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('chunking', 'Chunking'), ('embedding', 'Embedding'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', help_text='Status of vectorization process', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='vectorization_idempotency_key',
            field=models.CharField(blank=True, help_text='Idempotency key for vectorization operations', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['state'], name='knowledgeba_state_11a2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['vector_status'], name='knowledgeba_vector__d94235_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['upload_idempotency_key'], name='knowledgeba_upload__428bc3_idx'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledgebase.document'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='knowledgeba_documen_a7482e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['chunk_id'], name='knowledgeba_chunk_i_50a156_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['is_vectorized'], name='knowledgeba_is_vect_0eecee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_id')},
        ),
    ]
