# Generated by Django 5.2.8 on 2025-12-01 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0010_documentchunk_document_chunk_count_document_state_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='knowledgeba_upload__428bc3_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='upload_idempotency_key',
        ),
        migrations.RemoveField(
            model_name='document',
            name='vectorization_idempotency_key',
        ),
    ]
