# Generated by Django 5.2.8 on 2025-12-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0011_remove_document_knowledgeba_upload__428bc3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text'), ('docx', 'Word Document'), ('html', 'HTML'), ('url', 'URL')], max_length=10),
        ),
    ]
