# Generated by Django 5.2.8 on 2025-12-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0012_add_url_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='structured_text_qa_url',
            field=models.URLField(blank=True, help_text='URL to processed Q&A format structured text file (for PDFs)', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='structured_text_raw_url',
            field=models.URLField(blank=True, help_text='URL to raw extracted structured text file (for PDFs)', null=True),
        ),
    ]
