# Generated by Django 5.2.8 on 2025-12-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0013_add_structured_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='question',
            field=models.TextField(blank=True, help_text='Question label for this chunk (for Q&A format chunks)', null=True),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='text',
            field=models.TextField(help_text='Text content of the chunk (answer for Q&A format)'),
        ),
    ]
