# Generated by Django 5.2.8 on 2025-12-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0014_add_question_field_to_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if PDF processing failed', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('structuring', 'Structuring with LLM'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of PDF extraction and structuring process', max_length=20),
        ),
    ]
