# Generated by Django 5.2.8 on 2025-11-28 10:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, help_text='Our generated session ID', max_length=255, unique=True)),
                ('external_user_id', models.CharField(blank=True, db_index=True, help_text='Third-party user ID', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Session expiration time (24h default)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the session is active')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Device info, etc.')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='chats_sessi_session_0440a7_idx'), models.Index(fields=['external_user_id'], name='chats_sessi_externa_64b5bd_idx'), models.Index(fields=['is_active'], name='chats_sessi_is_acti_ec994c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='RAG sources, car results')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.session')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='chats_chatm_session_4625d4_idx'), models.Index(fields=['is_deleted'], name='chats_chatm_is_dele_b2f9f3_idx')],
            },
        ),
    ]
