# Generated by Django 5.2.8 on 2025-12-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Session expiration time (24h default, auto-set if not provided)', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Our generated session ID (auto-generated if not provided)', max_length=255, unique=True),
        ),
    ]
