# Generated by Django 5.2.8 on 2025-12-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_session_expires_at_alter_session_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Our generated session ID (auto-generated if not provided)', max_length=255, null=True, unique=True),
        ),
    ]
