# Generated by Django 5.2.8 on 2025-12-02 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_session_id_field'),
    ]

    operations = [
        # The index was already dropped in migration 0004, so we only update the state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Database operations already done in migration 0004
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='session',
                    name='chats_sessi_session_0440a7_idx',
                ),
                migrations.AlterField(
                    model_name='chatmessage',
                    name='session',
                    field=models.ForeignKey(db_column='session_id', help_text='Reference to the session (id field of Session model)', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.session'),
                ),
            ],
        ),
    ]
