# Generated by Django 5.2.8 on 2025-12-09 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_session_chats_sessi_session_0440a7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique visitor identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True, help_text='Last time visitor was active')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Browser info, IP, etc.')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='chats_visit_created_0548a4_idx')],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='visitor',
            field=models.ForeignKey(blank=True, help_text='Visitor this session belongs to (auto-created if not provided)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chats.visitor'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['visitor'], name='chats_sessi_visitor_6998ce_idx'),
        ),
    ]
