# Generated by Django 5.2.8 on 2025-12-09 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_populate_visitors'),  # Run data migration first to populate visitors
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='visitor',
            field=models.ForeignKey(help_text='Visitor this session belongs to (auto-created if not provided)', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chats.visitor'),
        ),
    ]
