# Generated by Django 5.2.8 on 2025-12-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_session_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='conversation_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores conversation-specific data (e.g., name, email, phone for sales/support)'),
        ),
        migrations.AddField(
            model_name='session',
            name='conversation_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('support', 'Support'), ('knowledge', 'Knowledge'), ('routing', 'Routing')], db_index=True, default='routing', help_text='Type of conversation: sales, support, knowledge, or routing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['conversation_type'], name='chats_sessi_convers_f39b6d_idx'),
        ),
    ]
