# Generated by Django 5.2.8 on 2025-12-10 15:52

from django.db import migrations


def set_default_conversation_type(apps, schema_editor):
    """Set default conversation_type for existing sessions."""
    Session = apps.get_model('chats', 'Session')
    # Update any sessions that might have NULL conversation_type
    Session.objects.filter(conversation_type__isnull=True).update(conversation_type='routing')
    # Also ensure conversation_data is set for any NULL values
    Session.objects.filter(conversation_data__isnull=True).update(conversation_data={})


def reverse_set_default_conversation_type(apps, schema_editor):
    """Reverse migration - no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_session_conversation_data_session_conversation_type_and_more'),
    ]

    operations = [
        migrations.RunPython(
            set_default_conversation_type,
            reverse_set_default_conversation_type
        ),
    ]
