# Generated by Django 5.2.8 on 2026-01-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_add_last_message_to_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='input_tokens',
            field=models.IntegerField(default=0, help_text='Number of input tokens used for this message'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='output_tokens',
            field=models.IntegerField(default=0, help_text='Number of output tokens used for this message'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='total_tokens',
            field=models.IntegerField(default=0, help_text='Total tokens used for this Q&A pair'),
        ),
        migrations.AddField(
            model_name='session',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when session ended', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='total_input_tokens',
            field=models.IntegerField(default=0, help_text='Total input tokens used in this session'),
        ),
        migrations.AddField(
            model_name='session',
            name='total_output_tokens',
            field=models.IntegerField(default=0, help_text='Total output tokens used in this session'),
        ),
        migrations.AddField(
            model_name='session',
            name='total_tokens',
            field=models.IntegerField(default=0, help_text='Total tokens used in this session'),
        ),
    ]
