# Generated by Django 5.2.8 on 2026-01-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_chatmessage_input_tokens_chatmessage_output_tokens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='input_tokens',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='output_tokens',
        ),
        migrations.RemoveField(
            model_name='session',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_input_tokens',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_output_tokens',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='completion_tokens',
            field=models.IntegerField(default=0, help_text='Number of completion tokens used'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='prompt_tokens',
            field=models.IntegerField(default=0, help_text='Number of prompt tokens used'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='token_source',
            field=models.CharField(blank=True, help_text='Source of token usage: embedding, chat, suggestion', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='total_completion_tokens',
            field=models.IntegerField(default=0, help_text='Total completion tokens used in this session'),
        ),
        migrations.AddField(
            model_name='session',
            name='total_prompt_tokens',
            field=models.IntegerField(default=0, help_text='Total prompt tokens used in this session'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='total_tokens',
            field=models.IntegerField(default=0, help_text='Total tokens used (prompt + completion)'),
        ),
        migrations.AlterField(
            model_name='session',
            name='total_tokens',
            field=models.IntegerField(default=0, help_text='Total tokens used in this session (prompt + completion)'),
        ),
    ]
