# Generated by Django 5.2.8 on 2026-02-05 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0015_alter_all_token_fields_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='completion_tokens',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='prompt_tokens',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='token_source',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='total_tokens',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_completion_tokens',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_prompt_tokens',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_tokens',
        ),
        migrations.CreateModel(
            name='MessageSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_text', models.CharField(help_text='The suggestion text displayed to the user', max_length=200)),
                ('suggestion_type', models.CharField(choices=[('rag_related', 'RAG Related Question'), ('contextual', 'Contextual Suggestion'), ('conversion', 'Conversion Action'), ('fallback', 'Fallback Suggestion')], default='contextual', help_text='Type of suggestion generated', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order of the suggestion (0-based)')),
                ('is_clicked', models.BooleanField(default=False, help_text='Whether this suggestion was clicked by the user')),
                ('clicked_at', models.DateTimeField(blank=True, help_text='When the suggestion was clicked', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata like RAG sources, generation method, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(help_text='The assistant message this suggestion belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='chats.chatmessage')),
            ],
            options={
                'verbose_name': 'Message Suggestion',
                'verbose_name_plural': 'Message Suggestions',
                'ordering': ['message', 'order'],
                'indexes': [models.Index(fields=['message', 'order'], name='chats_messa_message_298303_idx'), models.Index(fields=['suggestion_type'], name='chats_messa_suggest_57a137_idx'), models.Index(fields=['is_clicked'], name='chats_messa_is_clic_48f71d_idx'), models.Index(fields=['created_at'], name='chats_messa_created_b2d592_idx')],
                'unique_together': {('message', 'order')},
            },
        ),
    ]
