# Generated by Django 5.2.8 on 2026-02-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0016_remove_chatmessage_completion_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, help_text="User's email address", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, help_text='IP address for visitor identification', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='name',
            field=models.CharField(blank=True, help_text="User's name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, help_text="User's phone number", max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['ip_address'], name='chats_visit_ip_addr_c2516e_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['last_seen_at'], name='chats_visit_last_se_1cc267_idx'),
        ),
    ]
