# Generated by Django 5.2.8 on 2026-02-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0017_add_visitor_ip_and_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SNOOZED', 'Snoozed'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Session lifecycle status', max_length=10),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status'], name='chats_sessi_status_5cf30d_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['visitor', 'status'], name='chats_sessi_visitor_b8bb55_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status', 'created_at'], name='chats_sessi_status_b5a51a_idx'),
        ),
    ]
