# Generated by Django 5.2.8 on 2026-03-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0018_add_session_status_field'),
    ]

    operations = [
        # Undo 0018: Remove session status field and indexes
        migrations.RemoveIndex(
            model_name='session',
            name='chats_sessi_status_b5a51a_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='chats_sessi_visitor_b8bb55_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='chats_sessi_status_5cf30d_idx',
        ),
        migrations.RemoveField(
            model_name='session',
            name='status',
        ),
        
        # Undo 0017: Remove visitor indexes and fields
        migrations.RemoveIndex(
            model_name='visitor',
            name='chats_visit_last_se_1cc267_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitor',
            name='chats_visit_ip_addr_c2516e_idx',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='email',
        ),
    ]
