# Generated by Django 5.2.8 on 2025-12-08 06:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('api_url', models.URLField(default='https://api.yourdomain.com')),
                ('widget_url', models.URLField(default='https://cdn.yourdomain.com/widget')),
                ('features', models.JSONField(blank=True, default=dict)),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Widget Configuration',
                'verbose_name_plural': 'Widget Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WidgetAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key_hash', models.CharField(db_index=True, max_length=255, unique=True)),
                ('key_prefix', models.CharField(max_length=20)),
                ('name', models.CharField(help_text='Display name for the API key', max_length=255)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('allowed_domains', models.JSONField(blank=True, default=list, help_text='List of allowed domains for CORS validation')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Widget API Key',
                'verbose_name_plural': 'Widget API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status_code', models.IntegerField()),
                ('response_time', models.IntegerField(help_text='Response time in milliseconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='widget.widgetapikey')),
            ],
            options={
                'verbose_name': 'API Key Usage Log',
                'verbose_name_plural': 'API Key Usage Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='widgetapikey',
            index=models.Index(fields=['api_key_hash'], name='widget_api_key_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='widgetapikey',
            index=models.Index(fields=['organization_id'], name='widget_api_key_org_idx'),
        ),
        migrations.AddIndex(
            model_name='widgetapikey',
            index=models.Index(fields=['user'], name='widget_api_key_user_idx'),
        ),
        migrations.AddIndex(
            model_name='widgetapikey',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['is_active'], name='widget_api_key_active_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusagelog',
            index=models.Index(fields=['api_key', '-timestamp'], name='widget_apik_api_key_1c89c3_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusagelog',
            index=models.Index(fields=['organization_id', '-timestamp'], name='widget_apik_organiz_5787e2_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusagelog',
            index=models.Index(fields=['timestamp'], name='widget_apik_timesta_585482_idx'),
        ),
    ]
