# Generated by Django 5.2.8 on 2025-12-08 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgetconfig',
            name='organization_id',
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='api_key',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widget_config', to='widget.widgetapikey'),
        ),
    ]
